choco install powershell-core
choco install googlechrome
choco install vscode
choco install golang
choco install goreleaser
choco install 7zip
choco install awscli
choco install git
choco install neovim
choco install python
choco install setdefaultbrowser
